# Right now, don't need a deploy workflow, since the repo is hooked up to
# Netlify. Netlify will detect a merge.

name: Fast-Forward Main

on:
  workflow_dispatch:

jobs:
  merge-dev-to-main:
    name: Fast-Forward Merge dev to main
    if: ${{ github.ref_name == 'dev' }}
    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched for merging

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fast-Forward Merge
        run: |
          git checkout main
          git merge --ff-only origin/dev || {
            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
            exit 1;
          }
          git push origin main
