# Sync repo to the Forgejo mirror
name: Repo sync (GitHub -> Forgejo)
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync-repo-to-forgejo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Gather facts'
        run: |
          echo "Codeberg variables:"
          echo "  CODEBERG_PUSH_URL: ${{ vars.CODEBERG_PUSH_URL }}${{ vars.CODEBERG_REPO }}.git"
          echo "  CODEBERG_USERNAME: ${{ vars.CODEBERG_USERNAME }}"
      - name: 'Sync to Codeberg'
        uses: spyoungtech/mirror-action@master
        with:
          REMOTE: '${{ vars.CODEBERG_PUSH_URL }}${{ vars.CODEBERG_REPO }}.git'
          GIT_USERNAME: ${{ vars.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets._CODEBERG_TOKEN }}
